set(HEADERS ${HEADERS}
	include/Chiaroscuro.h
	include/Color.h
	include/ColorDesigner.h
	include/ColorPalette.h
	include/common/util.h
	include/common/uuid.h
	include/ImGui/ImGuiInputAdapter.h
	include/ImGui/ImGuiNavBar.h
	include/ImGui/ImGuiPresetSelector.h
	include/ImGui/ImGuiRenderer.h
	include/ImGui/ImGuiRenderTarget.h
	include/ImGui/ImGuiSelector.h
	include/ImGui/ImGuiTabBar.h
	include/ImGui/ImGuiTabBarAbstract.h
	include/ImGui/ImGuiValueEditor.h
	include/ImGui/ImGuiWidgets.h
	include/Input/DeviceKeyMapping.h
	include/Input/InputContext.h
	include/Input/InputFilter.h
	include/Input/InputModifier/BSControlModifier.h
	include/Input/InputModifier/BSKeyboardGamepadModifier.h
	include/Input/InputModifier/CanCharInput.h
	include/Input/InputModifier/CanMouseMove.h
	include/Input/InputModifier/CanMoveAround.h
	include/Input/InputModifier/CanRun.h
	include/Input/InputModifier/FreeCameraControl.h
	include/Input/InputModifier/FreeCameraZTranslate.h
	include/Input/InputModifier/InputModifier.h
	include/LightDesigner.h
	include/LightEditor.h
	include/Lighting.h
	include/LightingPreset.h
	include/MCM/Settings.h
	include/MenuInputContext.h
	include/MenuState/MenuHidden.h
	include/MenuState/MenuItemActive.h
	include/MenuState/MenuLookingAround.h
	include/MenuState/MenuOpen.h
	include/MenuState/MenuPositioning.h
	include/MenuState/MenuState.h
	include/MyEnumSet.h
	include/PCH.h
	include/Preset/Preset.h
	include/Preset/PresetDatabase.h
	include/Preset/PresetSerializationControl.h
	include/Preset/SerializationStrategy.h
	include/RE.h
	include/SKSE/CoSaveIO.h
	include/SKSE/SerializableCollection.h
	include/SKSE/SerializationControl.h
)
