set(HEADERS ${HEADERS}
	include/PCH.h
	include/ImGui/ImGuiRenderer.h
	include/ImGui/ImGuiRenderTarget.h
	include/ImGui/ImGuiInputAdapter.h
	include/ImGui/ImGuiTabBar.h
	include/ImGui/ImGuiTabBarAbstract.h
	include/Chiaroscuro.h
	include/ImGui/ImGuiWidgets.h
	include/Lighting.h
	include/LightingPreset.h
	include/ImGui/ImGuiPresetSelector.h
	include/RE.h
	include/Preset/PresetDatabase.h
	include/Preset/SerializationStrategy.h
	include/Preset/PresetSerializationControl.h
	include/ImGui/ImGuiNavBar.h
	include/Preset/Preset.h
	include/Color.h
	include/uuid.h
	include/MyEnumSet.h
	include/ImGui/ImGuiValueEditor.h
	include/ColorPalette.h
	include/LightEditor.h
	include/ColorDesigner.h
	include/ImGui/ImGuiSelector.h
	include/LightDesigner.h
	include/SKSE/SerializableCollection.h
	include/SKSE/SerializationControl.h
	include/SKSE/CoSaveIO.h
)
