set(HEADERS ${HEADERS}
	include/PCH.h
	include/ImGui/ImGuiRenderer.h
	include/ImGui/ImGuiComponent.h
	include/ImGui/ImGuiInputAdapter.h
	include/ImGui/ImGuiTabBar.h
	include/ImGui/ImGuiTabBarAbstract.h
	include/SceneCraft.h
	include/ImGui/ImGuiWidgets.h
	include/Prop.h
	include/Lighting.h
	include/LightingPreset.h
	include/ImGui/ImGuiSelector.h
	include/RE.h
	include/Preset/PresetDatabase.h
	include/Preset/SerializationStrategy.h
	include/Preset/PresetSerializationControl.h
	include/ImGui/ImGuiNavBar.h
	include/Preset/Preset.h
	include/Color.h
	include/Preset/uuid.h
	include/MyEnumSet.h
)
