set(SOURCES ${SOURCES}
	src/Chiaroscuro.cpp
	src/Color.cpp
	src/ColorDesigner.cpp
	src/ColorPalette.cpp
	src/ImGui/ImGuiInputAdapter.cpp
	src/ImGui/ImGuiNavBar.cpp
	src/ImGui/ImGuiRenderer.cpp
	src/ImGui/ImGuiRenderTarget.cpp
	src/ImGui/ImGuiTabBarAbstract.cpp
	src/ImGui/ImGuiWidgets.cpp
	src/Input/InputContext.cpp
	src/Input/InputModifier/BSControlModifier.cpp
	src/Input/InputModifier/CanCharInput.cpp
	src/Input/InputModifier/CanMouseButton.cpp
	src/Input/InputModifier/CanMouseMove.cpp
	src/Input/InputModifier/CanMoveAround.cpp
	src/Input/InputModifier/FreeCameraControl.cpp
	src/Input/InputModifier/InputModifier.cpp
	src/LightDesigner.cpp
	src/LightEditor.cpp
	src/Lighting.cpp
	src/LightingPreset.cpp
	src/main.cpp
	src/MenuInputContext.cpp
	src/Preset/Preset.cpp
	src/Preset/PresetDatabase.cpp
	src/Preset/PresetSerializationControl.cpp
	src/RE.cpp
	src/SKSE/CoSaveIO.cpp
	src/SKSE/SerializationControl.cpp
)
