set(SOURCES ${SOURCES}
	src/main.cpp
	src/ImGui/ImGuiRenderer.cpp
	src/Chiaroscuro.cpp
	src/ImGui/ImGuiComponent.cpp
	src/ImGui/ImGuiInputAdapter.cpp
	src/ImGui/ImGuiWidgets.cpp
	src/ImGui/ImGuiNavBar.cpp
	src/Lighting.cpp
	src/LightingPreset.cpp
	src/RE.cpp
	src/Preset/PresetDatabase.cpp
	src/Preset/Preset.cpp
	src/Color.cpp
	src/Preset/PresetSerializationControl.cpp
	src/ColorPalette.cpp
	src/LightEditor.cpp
	src/ColorDesigner.cpp
	src/ImGui/ImGuiTabBarAbstract.cpp
	src/LightDesigner.cpp
	src/SKSE/SerializationControl.cpp
	src/SKSE/CoSaveIO.cpp
)
